@baseUrl = http://localhost:3000
@authToken = {{authenthicate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Valid name 2",
  "email": "valid_mail2@mail.com",
  "password": "validPassword@123456"
}

###
# @name authenthicate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "valid_mail@mail.com",
  "password": "validPassword@123456"
}

###
# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "nova pergunta 6",
  "content": "conteudo da pergunta"
  
}

###
# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
